repository:
  name: episode
  description: 开源面对面，连接热爱开源的你！Episodes for the open-source face-to-face talk!
  homepage: https://www.ximalaya.com/gerenchengzhang/53320813/
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: newbie
    color: abe7f4
    description: 新手上路
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: feature
    color: ffc6a3
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: Hacktoberfest
    description: More details from https://hacktoberfest.digitalocean.com/
    color: 5ce05e
  - name: chore
    color: c2c2fc
  - name: priority-high
    color: D93F0B
  - name: priority-medium
    color: FBCA04
  - name: priority-low
    color: 006B75
  - name: 嘉宾推荐
    color: 1d76db
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      restrictions:
        users: []
        teams: []
